import {initSocket} from "@/lib/socket";
import "./globals.css";
import SideNavbar from "@/components/SideNavBar";


export const metadata = {
    title: "SpiritX_x-coders_02",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    if (typeof window === "undefined") {
    }

    return (
        <html lang="en">
        <body className="bg-gray-100 flex">
        <SideNavbar/>
        <main className="flex-1 ml-16 transition-all duration-300 ease-in-out">
            {children}
        </main>
        </body>
        </html>
    );
}